# make a new micromamba environment solely for this project

name: mrt
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - streamlit>=1.28
  - pandas>=2.0
  - numpy>=1.24
  - plotly>=5.15
  - seaborn>=0.12
  - matplotlib>=3.7

